projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/graphql/types.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/types.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: lgwvj6xswbhg5bzt2ysxxszqcu
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
